### ISSUE TITLE
seriously consider renaming this project to opentracing

### ISSUE THREAD

**Issue by basvanbeek** [gin-contrib/opengintracing#2]
OpenTracing != Tracing. 

If Gin gets contributions for other Tracing API's like native Zipkin, SkyWalking or OpenCensus we really should be more careful with naming. This name adds to the confusion of many people in the field thinking OpenTracing is synonymous with the much larger field of Tracing.

**Comment by xakep666** [comment]
Repo name chosen by @appleboy . I`m also think that current name is not good and don`t mind renaming

**Comment by xakep666** [comment]
@appleboy I think "opengintracing" will be good name for repo

**Comment by appleboy** [comment]
@xakep666 @basvanbeek rename to `opengintracing`

**Comment by bcho** [comment]
But the repo's import path is tracing, it's unable to use by default, should the package name be fixed too?

**Comment by appleboy** [comment]
@bcho I updated the readme to fix import path.

See https://github.com/gin-contrib/opengintracing/commit/4d7eeefd9cddc65129048d0434c73360fdbea929

**Comment by bcho** [comment]
But the package name is still tracing? https://github.com/gin-contrib/opengintracing/blob/master/tracing.go

**Comment by appleboy** [comment]
We can't change the package name. It is duplicate of opentracing/opentracing-go library.

**Comment by bcho** [comment]
I think the package name should be opengintracing not opentracing

**Comment by appleboy** [comment]
@bcho Done. rename `tracing` to `opengintracing`.
